sonar.projectKey=Charan-kumarr_potato-disease-devops
sonar.projectName=Potato Disease DevOps
sonar.sources=.
sonar.host.url=http://localhost:9000
sonar.token=sqp_f56f777b1ab8e2618e86a5edb813f8490b97863
