sonar.projectKey=potato-app
sonar.projectName=Potato Plant Disease Recognition
sonar.projectVersion=1.0

sonar.sources=.

sonar.host.url=http://localhost:9000


sonar.token=sqp_a288fff449d1f9423a0e40d25d5659edfb66edc7



