sonar.projectKey=potato-plant-disease-recognition
sonar.projectName=Potato Plant Disease Recognition
sonar.sources=.
sonar.host.url=http://localhost:9000
sonar.token=sqp_a479ecab01c63ccb77d25ef1be056ae0f7561b3e
